Repository LikeLion13-Central-Team1/FrontEnd, pull requests merged in 2025-08, with the labels that each got.

#6 refactor/아이콘 업로드, 기본 폼 생성, 불필요한 파일 삭제 (#5)
  css/auth/signup.css
  css/style.css
  images/ai.png
  images/ai_black.png
  images/arrow_down.png
  images/arrow_left.png
  images/arrow_right.png
  images/buythis.png
  images/cart.png
  images/delete.png
  images/gps.png
  images/gps_black.png
  images/gps_red.png
  images/group.png
  images/heart.png
  images/heart_red.png
  images/home.png
  images/home_red.png
  images/info.png
  images/iphone.png
  images/iphone_black.png
  images/iphone_home.png
  images/like.png
  images/like_red.png
  images/like_yellow.png
  images/menu.png
  images/menu_red.png
  images/my.png
  images/my_black.png
  images/my_white.png
  images/order.png
  images/order_red.png
  images/pencil.png
  images/pickup.png
  images/review.png
  images/search.png
  images/shop.png
  images/shoplist.png
  images/shoplist_red.png
  images/star.png
  js/auth/signup.js
  pages/auth/signup.html
  pages/test.html
Labels: ♻️refactor

#10 feat: 로그인 대체 화면 개발
  css/login.css
  images/heart.png
  images/heart.svg
  images/home.png
  images/home.svg
  images/login_logo.svg
  images/my.png
  images/my.svg
  images/my_black.png
  images/my_black.svg
  images/shop.png
  images/shop.svg
  images/shoplist.png
  images/shoplist.svg
  index.html
  js/login.js
  js/test_home.js
  pages/login.html
  pages/store_home.html
  pages/test.html
  pages/test_home.html
Labels: ✨feature

#12 refactor: 사용자페이지 SVG로 대체(#11)
  css/gps_enroll.css
  css/gps_set.css
  images/arrow_down.png
  images/arrow_down.svg
  images/arrow_left.png
  images/arrow_left.svg
  images/buythis.png
  images/cart.png
  images/cart.svg
  images/gps.png
  images/gps.svg
  images/gps_black.png
  images/gps_black.svg
  images/gps_red.png
  images/gps_red.svg
  images/heart_red.png
  images/heart_red.svg
  images/home_red.png
  images/home_red.svg
  images/like.png
  images/like.svg
  images/like_red.png
  images/like_red.svg
  images/like_yellow.png
  images/like_yellow.svg
  images/pencil.png
  images/pencil.svg
  images/plus.png
  images/plus.svg
  images/search.png
  images/search.svg
  images/shoplist_red.png
  images/shoplist_red.svg
  images/star.png
  images/star.svg
  pages/gps_enroll.html
  pages/gps_set.html
Labels: ♻️refactor

#19 feat: 가게페이지 화면 개발
  .idea/.gitignore
  .idea/FrontEnd.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  css/store_home.css
  images/ai_black.png
  images/ai_black.svg
  images/arrow_right.png
  images/arrow_right.svg
  images/group.png
  images/group.svg
  images/info.png
  images/info.svg
  js/store_home.js
  pages/store_home.html
Labels: ✨feature

#22 refactor: 배경 색 변경 (#21)
  css/style.css
Labels: ♻️refactor

#23 ✨feat: 남은 담당 페이지 화면 개발 완료
  css/cart.css
  css/customer_review.css
  css/order.css
  css/pickup.css
  css/reservation.css
  css/store_home.css
  images/delete.png
  images/delete.svg
  images/reservation.svg
  js/cart.js
  js/customer_review.js
  js/order.js
  js/pickup.js
  js/reservation.js
  pages/cart.html
  pages/customer_review.html
  pages/order.html
  pages/pickup.html
  pages/reservation.html
Labels: ♻️refactor, ✨feature

#45 feat: 랜딩페이지, 메뉴조회, 리뷰올리기(#44)
  css/index.css
  images/landing_1.png
  images/landing_4.png
  index.html
  js/home_menu.js
  js/purchase_log.js
  js/write_review.js
Labels: ✨feature

#49 refactor: pickup.js에 시간 제약 코드 추가
  js/pickup.js
Labels: ♻️refactor
